version: "2"
services:
  web:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/cfp-app:/client
  database:
    build: ./database
#    image: mongo:3.4.0
    ports:
      - "27000:27017"
#    entrypoint: [mongod --bind_ip 0.0.0.0 --port 27017, ./setup-indices.sh]
#    entrypoint: mongod --bind_ip 0.0.0.0 --port 27017
    entrypoint: "./setup-db.sh"
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server
    working_dir: /server
    entrypoint: "python -m flask run --host=0.0.0.0"
    depends_on:
      - database
